### ISSUE TITLE
PinWin doesn't want to run

### ISSUE THREAD

**Issue by Spb8Lighting** [Bluegrams/PinWin#2]
Since the last update v0.2 PinWin doesn't want to run on my PC (Windows 10 with latest update).

Installed done through the MSI package.

Another information, this new MSI package seems to not be signed, as Windows prevent me to run it, where the v0.1 MSI package doesn't have any warning.

v0.1 just works like a charm, thanks a lot!!!

**Comment by alxnull** [comment]
Thanks for reporting. Could you try to do a clean uninstall of PinWin and then reinstall version v.0.2 using the MSI package?

**Edit:** I pushed a new update (v.0.2.1) with some bug fixes. You may want to try if that fixes the issue.

**Comment by Spb8Lighting** [comment]
Hi ! Thanks for the quick fix, it works like a charm now :)
