### ISSUE TITLE
Request: Checksums sha256, md5 etc.

### ISSUE THREAD

**Issue by ontoast** [Bluegrams/PinWin#6]
Could hash checksums (such as md5, sha256, etc.) for each download please be added to these resources? 

This supposedly helps to determine that a file being downloaded is the same as the one being published by the author.

**Comment by alxnull** [comment]
The binary packages on SourceForge (which are the only official currently) already provide SHA1 & MD5 checksums (e.g. https://sourceforge.net/projects/pinwin/files/v.0.2.2/), so you can check your download with those. Does this suffice or in which other place do you think it would be useful to add checksums?

**Comment by ontoast** [comment]
How are the SHA1 and MD5 checksums provided? I don't see them listed anywhere in the link you've given. Thanks.

**Comment by alxnull** [comment]
In the download file listing, you can show them by clicking on the circled "i" to the right of each file. It should look like this:

![grafik](https://user-images.githubusercontent.com/26907770/103437355-17b36380-4c27-11eb-95bb-c138883b44af.png)

**Comment by ontoast** [comment]
alxnull, thank you. 👍
