### ISSUE TITLE
Chocolatey returned 0 packages

### ISSUE THREAD

**Issue by Varlorg** [Bluegrams/PinWin#7]
Hi,
I just found pinwin as i was searching for alternative to deskpin. 
I was happily surprise to see the section "Install from Chocolatey: choco install pinwin"
but there is 0 package found. ( https://chocolatey.org/packages?q=PinWin )

Thanks

**Comment by alxnull** [comment]
Hi, 

I re-uploaded the package the package to Chocolatey a few weeks ago. It finally got accepted now, so you should be able to install it now.
